export interface ICategory {
  id: string;
  name: string;
  description?: any;
  imageUrl: string;
  createdOn: string;
}

// Generated by https://quicktype.io

export interface CategoryResponse {
  message: string;
  status: string;
  data: ICategory[];
}
