import { ResponseModel } from './../shared/models/ResponseModel';
export interface IUserModel {}
export interface IUser {
  id: string;
  firstName?: any;
  lastName?: any;
  profileImageUrl?: any;
  bio?: string;
  email: string;
  address: string;
  alpha2CountryCode: string;
  state: string;
  phoneNumber: string;
  city: string;
  scope: string;
  preferredProfileType: string;
  businessName: string;
  businessAddress: string;
  businessEmail: string;
  businessPhone: string;
  businessCountryCode: string;
  businessState: string;
  businessCity: string;
  businessLogoUrl: string;
  businessWebsite: string;
  businessPhoneConfirmed: boolean;
  businessSocialLinks: { twitter: string; facebook: string; instagram: string };
  businessRegistrationNumber: string;
  isSellerApproved: boolean;
  sellerApprovalStatus: string;
  emailConfirmed: boolean;
  phoneNumberConfirmed: boolean;
}

export interface IUserResponse extends ResponseModel {
  data: IUser;
}

export interface UserDataResponse {
  data: IUser;
  message: string;
  status: string;
}

// Generated by https://quicktype.io

export interface IUpdateUser {
  id: string;
  firstName: string;
  lastName: string;
  address: string;
  alpha2CountryCode: string;
  state: string;
  phoneNumber: string;
  city: string;
  scope: string[];
}
