import { IResponseModel } from "../shared/models/IResponseModel";
// Generated by https://quicktype.io

export interface RegisterModel {
  email: string;
  password: string;
  confirmPassword: string;
  firstName: string;
  lastName: string;
  // profileImageUrl: string;
}

// Generated by https://quicktype.io

export interface RegisterResponseModel extends IResponseModel {
  data: RegisterResponse;
}
export interface RegisterResponse {
  canLogin: boolean;
}
