// Generated by https://quicktype.io

export interface IResponseModel  {
  message: string;
  status:  string;
  data:    object;
}


export const ResponseStatus = {
  success: 'success',
  fail: 'fail'
};
