// Generated by https://quicktype.io

export interface IResponseModel {
  message: string;
  status: string;
  data: object;
}

export interface ApiResponse<T = null> {
  message: string;
  status: string;
  data: T;
}

export const ResponseStatus = {
  success: 'success',
  fail: 'fail',
};

export interface GetWssUrlResponse {
  wssUrl: string;
}
