// Generated by https://quicktype.io

import { IResponseModel } from "./IResponseModel";

export class ResponseModel implements IResponseModel {
  message: string;
  status:  string;
  data:    object;
}



