// Generated by https://quicktype.io

export interface MakeCartPaymentRequestModel {
  userId: string;
  referenceId: string;
  currencyCode: string;
  paymentProviderCode: string;
}

// Generated by https://quicktype.io

export interface MakeCartPaymentResponseModel {
  message: string;
  status: string;
  data: Data;
  code: null;
  errors: null;
}

export interface Data {
  redirectUrl: string;
}

// Generated by https://quicktype.io

export interface GetCartPaymentMethodResponse {
  message: string;
  status: string;
  data: CartPaymentMethod[];
  code: string;
  errors: string[];
}

export interface CartPaymentMethod {
  code: string;
  name: string;
  description: string;
  imageUrl: string;
  currencies: string[];
  canPayout: boolean;
  canRecieveFund: boolean;
  id: string;
}
