// Generated by https://quicktype.io

export interface GetCartResponseModel {
  message: string;
  status: string;
  data: CartData;
  code: string;
  errors: string[];
}

export interface CartData {
  userId: string;
  referenceId: string;
  promoCode: string;
  discount: number;
  totalCost: number;
  paymentReferenceNo: string;
  shippingCost: ShippingCost;
  cartItems: CartItem[];
  subTotal: number;
  id: string;
  createdOn: string;
  updatedOn: string;
  isActive: boolean;
  isDeleted: boolean;
}

export interface CartItem {
  productId: string;
  product: Product;
  unit: number;
  destination: Destination;
  logistic: Logistic;
  paymentOption: string;
  varations: ComplementaryProduct[];
  complementaryProducts: ComplementaryProduct[];
  logisticCode: string;
  shippingCost: ShippingCost;
  discount: number;
  total: number;
}

export interface ComplementaryProduct {
  id: string;
  productId: string;
  title: string;
  value: string;
  shortDescription: string;
  imageUrl: string;
  cost: number;
  isMultiple: boolean;
}

export interface Destination {
  firstname: string;
  lastname: string;
  lat: number;
  lng: number;
  countryCode: string;
  city: string;
  state: string;
  fullAddress: string;
  phoneNumber: string;
}

export interface Logistic {
  logisticId: string;
  logisticCode: string;
  logisticLogo: string;
  logisticName: string;
  estimateShippingCost: number;
}

export interface Product {
  name: string;
  price: number;
  categoryId: string;
  category: null;
  imageUrl: string;
  weight: number;
  paymentOptions: string;
  id: string;
  createdOn: string;
  previousPrice: number;
}

export interface ShippingCost {
  cost: number;
  discount: number;
}
