export const editorDefaultConfig = {
  toolbar: {
    items: [
      "heading",
      "style",
      "fontFamily",
      "|",
      "bold",
      "underline",
      "italic",
      "fontSize",
      "fontColor",
      "fontBackgroundColor",
      "|",
      "bulletedList",
      "numberedList",
      "outdent",
      "indent",
      "alignment",
      "|",
      "link",
      "blockQuote",
      "insertTable",
      "imageUpload",
      "imageInsert",
      "mediaEmbed",
      "undo",
      "redo",
      "findAndReplace",
    ],
  },
  language: "en",
  image: {
    toolbar: [
      "imageTextAlternative",
      "toggleImageCaption",
      "imageStyle:inline",
      "imageStyle:block",
      "imageStyle:side",
    ],
  },
  table: {
    contentToolbar: [
      "tableColumn",
      "tableRow",
      "mergeTableCells",
      "tableCellProperties",
      "tableProperties",
    ],
  },
  placeholder: "Type something here",
};
